org.gradle.jvmargs=-Xms128m -Xmx1024m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=96m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapBaseMinAddress=4g -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.daemon.jvmargs=-Xmx384m
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=false
