org.gradle.jvmargs=-Xms64m -Xmx768m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=64m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.daemon.jvmargs=-Xmx256m
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
